// Shared project data + i18n strings
const PROJECTS = [
  {
    id: 'subsilence',
    title: 'Subsilence',
    category: 'GAME',
    year: '2024',
    role: { fr: 'AI / Gameplay', en: 'AI / Gameplay' },
    team: '15 personnes / people',
    duration: { fr: '8 mois', en: '8 months' },
    engine: 'Unreal Engine 5',
    tech: ['Unreal Engine 5', 'Blueprints', 'C++', 'Niagara'],
    image: 'assets/subsilence.png',
    tagline: {
      fr: 'Horreur sous-marine. Survivre au silence.',
      en: 'Underwater horror. Survive the silence.',
    },
    description: {
      fr: "Subsilence est un jeu d'horreur en vue subjective situé dans une station de recherche abyssale. Le joueur doit progresser dans un complexe inondé en gérant son oxygène, sa lampe et le bruit qu'il produit — chaque son attire ce qui rôde dans l'obscurité.",
      en: "Subsilence is a first-person horror game set in an abyssal research station. The player navigates a flooded complex while managing oxygen, light and the noise they produce — every sound draws what lurks in the dark.",
    },
    challenges: {
      fr: "Concevoir une boucle de tension où le silence devient une mécanique. J'ai prototypé le système d'IA réactive au son et le pacing du level central.",
      en: "Designing a tension loop where silence itself becomes a mechanic. I prototyped the sound-reactive AI and paced the central level.",
    },
    pillars: [
      { fr: 'IA réactive au son', en: 'Sound-reactive AI' },
      { fr: 'Gestion de ressources', en: 'Resource management' },
      { fr: 'Narration environnementale', en: 'Environmental storytelling' },
    ],
  },
  {
    id: 'rosedeep',
    title: '4 Rosedeep Lane',
    category: 'GAME',
    year: '2023',
    role: { fr: 'Game Designer & Programmeur', en: 'Game Designer & Programmer' },
    team: '4 personnes / people',
    duration: { fr: '3 mois', en: '3 months' },
    engine: 'Unity',
    tech: ['Unity', 'C#', 'Cinemachine', 'Shader Graph'],
    image: 'assets/rosedeep.png',
    tagline: {
      fr: "Une enquête lente dans une maison qui ne devrait pas exister.",
      en: "A slow investigation inside a house that should not exist.",
    },
    description: {
      fr: "Aventure narrative dans une maison victorienne où les pièces se réorganisent entre deux passages. Le joueur reconstitue une affaire criminelle à travers des indices physiques et des souvenirs sonores.",
      en: "A narrative adventure inside a Victorian house whose rooms rearrange between visits. The player reconstructs a criminal case through physical clues and sound memories.",
    },
    challenges: {
      fr: "Le système de réagencement procédural des pièces tout en gardant une narration cohérente. Pipeline de scripting des indices.",
      en: "The procedural room-shuffling system while keeping narrative coherence. Clue scripting pipeline.",
    },
    pillars: [
      { fr: 'Maison non-euclidienne', en: 'Non-euclidean house' },
      { fr: 'Enquête déductive', en: 'Deductive investigation' },
      { fr: 'Audio diégétique', en: 'Diegetic audio' },
    ],
  },
  {
    id: '3fabz',
    title: '3 FABZ',
    category: 'GAME',
    year: '2023',
    role: { fr: 'Programmeur Gameplay', en: 'Gameplay Programmer' },
    team: '6 personnes / people',
    duration: { fr: '2 mois', en: '2 months' },
    engine: 'Unity',
    tech: ['Unity', 'C#', 'Photon', 'Animator'],
    image: 'assets/3fabz.jpg',
    tagline: {
      fr: "Party-game versus, chaotique et rapide.",
      en: "Versus party-game, chaotic and fast.",
    },
    description: {
      fr: "Trois joueurs s'affrontent dans des arènes courtes basées sur des règles changeantes à chaque manche. Concentré sur le feel : input, hitstop, particules.",
      en: "Three players battle across short arenas with rules that change every round. Focused on game feel: input, hitstop, particles.",
    },
    challenges: {
      fr: "Synchroniser le réseau et les effets locaux pour qu'aucun coup ne paraisse 'mou'.",
      en: "Sync networking with local effects so no hit ever feels mushy.",
    },
    pillars: [
      { fr: 'Multijoueur local + en ligne', en: 'Local + online multiplayer' },
      { fr: 'Game feel', en: 'Game feel' },
      { fr: 'Règles modulaires', en: 'Modular rule sets' },
    ],
  },
  {
    id: 'solar',
    title: 'Solar System',
    category: 'GAME',
    year: '2022',
    role: { fr: 'Programmeur solo', en: 'Solo programmer' },
    team: 'Solo',
    duration: { fr: '6 semaines', en: '6 weeks' },
    engine: 'Unity',
    tech: ['Unity', 'C#', 'URP'],
    image: 'assets/solar.png',
    tagline: {
      fr: "Simulation gravitationnelle interactive.",
      en: "Interactive gravitational simulation.",
    },
    description: {
      fr: "Bac à sable orbital où l'on place des planètes et lune et où l'on observe le système se stabiliser ou s'effondrer. Calcul N-corps temps réel.",
      en: "Orbital sandbox where you place planets and moons and watch the system stabilize or collapse. Real-time N-body computation.",
    },
    challenges: { fr: "Stabilité numérique de la simulation à grande vitesse de jeu.", en: 'Numerical stability of the simulation at high game speeds.' },
    pillars: [
      { fr: 'Physique N-corps', en: 'N-body physics' },
      { fr: 'Bac à sable', en: 'Sandbox' },
    ],
  },
  {
    id: 'rubiks',
    title: "Rubik's Cube",
    category: 'GAME',
    year: '2022',
    role: { fr: 'Programmeur solo', en: 'Solo programmer' },
    team: 'Solo',
    duration: { fr: '3 semaines', en: '3 weeks' },
    engine: 'Unity',
    tech: ['Unity', 'C#'],
    image: 'assets/rubiks.gif',
    tagline: { fr: "Rubik's Cube 3D jouable et résolvable.", en: "Playable & solvable 3D Rubik's cube." },
    description: {
      fr: "Cube fonctionnel avec rotation des faces à la souris, détection de l'état résolu, et solveur automatique optionnel.",
      en: "Functional cube with mouse-driven face rotation, solved-state detection, and an optional auto-solver.",
    },
    challenges: { fr: "Représentation propre de l'état du cube et permutations 3D.", en: 'Clean cube state representation and 3D permutations.' },
    pillars: [{ fr: 'Manipulation 3D', en: '3D manipulation' }, { fr: 'Algorithme de résolution', en: 'Solving algorithm' }],
  },
  {
    id: 'dungeon',
    title: 'ThisIsMyDungeon',
    category: 'GAME',
    year: '2023',
    role: { fr: 'Game Designer & Programmeur', en: 'Game Designer & Programmer' },
    team: '3 personnes / people',
    duration: { fr: '2 mois', en: '2 months' },
    engine: 'Unity',
    tech: ['Unity', 'C#', '2D'],
    image: 'assets/thisismydungeon.png',
    tagline: { fr: "Tower-defense vu côté donjon.", en: 'Tower-defense seen from the dungeon side.' },
    description: {
      fr: "On joue le maître du donjon : on place pièges et créatures pour repousser des aventuriers. Économie, runs procéduraux, et upgrades persistants.",
      en: "You play the dungeon master: place traps and creatures to repel adventurers. Economy, procedural runs, persistent upgrades.",
    },
    challenges: { fr: "Équilibrage de l'économie et de la difficulté entre runs.", en: 'Balancing economy and difficulty across runs.' },
    pillars: [{ fr: 'Tower-defense inversé', en: 'Reverse tower-defense' }, { fr: 'Méta-progression', en: 'Meta-progression' }],
  },
  {
    id: 'neko',
    title: 'Hungry Neko',
    category: 'GAME',
    year: '2022',
    role: { fr: 'Programmeur solo', en: 'Solo programmer' },
    team: 'Solo',
    duration: { fr: '2 semaines', en: '2 weeks' },
    engine: 'Unity',
    tech: ['Unity', 'C#', '2D'],
    image: 'assets/hungryneko.png',
    tagline: { fr: 'Mini arcade game félin.', en: 'Feline arcade mini game.' },
    description: {
      fr: 'Petit jeu de score : un chat affamé doit attraper le maximum de poissons en évitant les obstacles.',
      en: 'Small score game: a hungry cat must catch as many fish as possible while dodging obstacles.',
    },
    challenges: { fr: 'Itérer rapidement sur le feel et la difficulté.', en: 'Iterating fast on feel and difficulty.' },
    pillars: [{ fr: 'Score arcade', en: 'Arcade score' }],
  },
  {
    id: 'pandor',
    title: 'Pandor Engine',
    category: 'ENGINE',
    year: '2024',
    role: { fr: 'Engine Programmer', en: 'Engine Programmer' },
    team: '4 personnes / people',
    duration: { fr: '8 mois', en: '8 months' },
    engine: 'C++',
    tech: ['C++', 'OpenGL', 'PhysX', 'ImGui', 'Lua'],
    image: 'assets/pandor.png',
    tagline: { fr: 'Moteur de jeu maison, modulaire et orienté véhicule.', en: 'Home-grown engine, modular and vehicle-oriented.' },
    description: {
      fr: "Moteur 3D développé from scratch en C++ : ECS, renderer OpenGL avec PBR, intégration PhysX (notamment vehicle SDK), scripting Lua, éditeur en ImGui. Conçu pour prototyper rapidement des jeux de conduite arcade.",
      en: 'A 3D engine built from scratch in C++: ECS, an OpenGL PBR renderer, PhysX integration (incl. vehicle SDK), Lua scripting, ImGui editor. Designed to prototype arcade driving games quickly.',
    },
    challenges: { fr: "Architecture ECS performante + intégration véhicule réaliste sans se perdre dans la stack physique.", en: 'A performant ECS plus realistic vehicle integration without drowning in the physics stack.' },
    pillars: [
      { fr: 'ECS maison', en: 'Custom ECS' },
      { fr: 'PBR + IBL', en: 'PBR + IBL' },
      { fr: 'Vehicle SDK', en: 'Vehicle SDK' },
      { fr: 'Éditeur ImGui', en: 'ImGui editor' },
    ],
  },
  {
    id: 'procedural',
    title: 'Procedural Generation',
    category: 'TOOL',
    year: '2023',
    role: { fr: 'Tool Developer', en: 'Tool Developer' },
    team: 'Solo',
    duration: { fr: '4 semaines', en: '4 weeks' },
    engine: 'Unity',
    tech: ['Unity', 'C#', 'Wave Function Collapse'],
    image: 'assets/procedural.gif',
    tagline: { fr: 'Génération procédurale de niveaux par contraintes.', en: 'Constraint-based procedural level generation.' },
    description: {
      fr: "Outil Unity utilisant Wave Function Collapse pour générer des cartes en tuiles. Interface d'édition des règles d'adjacence, prévisualisation live, export en prefab.",
      en: 'Unity tool using Wave Function Collapse to generate tile-based maps. Adjacency rule editor, live preview, prefab export.',
    },
    challenges: { fr: 'Résolution rapide des contraintes pour rester interactif.', en: 'Fast constraint solving to stay interactive.' },
    pillars: [{ fr: 'Wave Function Collapse', en: 'Wave Function Collapse' }, { fr: 'Outil designer-friendly', en: 'Designer-friendly tool' }],
  },
  {
    id: 'chess',
    title: 'Chess Multiplayer',
    category: 'TOOL',
    year: '2023',
    role: { fr: 'Programmeur réseau', en: 'Network programmer' },
    team: 'Solo',
    duration: { fr: '3 semaines', en: '3 weeks' },
    engine: 'Unity',
    tech: ['Unity', 'C#', 'Mirror Networking'],
    image: 'assets/chess.png',
    tagline: { fr: 'Jeu d\'échecs en ligne, deux joueurs.', en: 'Online two-player chess.' },
    description: {
      fr: "Implémentation complète des règles d'échecs (incl. roque, prise en passant, promotion) avec mode 1v1 en ligne via Mirror.",
      en: 'Full chess rules (incl. castling, en passant, promotion) with online 1v1 via Mirror.',
    },
    challenges: { fr: 'Validation des coups côté serveur, anti-triche basique.', en: 'Server-side move validation, basic anti-cheat.' },
    pillars: [{ fr: 'Networking', en: 'Networking' }, { fr: 'Règles complètes', en: 'Full rule set' }],
  },
  {
    id: 'pacman',
    title: 'PacMan AI',
    category: 'TOOL',
    year: '2022',
    role: { fr: 'Programmeur IA', en: 'AI programmer' },
    team: 'Solo',
    duration: { fr: '3 semaines', en: '3 weeks' },
    engine: 'Unity',
    tech: ['Unity', 'C#', 'A*', 'FSM'],
    image: 'assets/pacman.png',
    tagline: { fr: 'IA des fantômes inspirée du PacMan original.', en: 'Ghost AI inspired by original PacMan.' },
    description: {
      fr: 'Réimplémentation des comportements de Blinky, Pinky, Inky et Clyde avec leurs cibles spécifiques. Visualisation des paths en temps réel.',
      en: 'Re-implementation of Blinky, Pinky, Inky and Clyde with their specific targeting. Live path visualization.',
    },
    challenges: { fr: 'Reproduire fidèlement le comportement de chaque fantôme.', en: 'Faithfully reproduce each ghost behaviour.' },
    pillars: [{ fr: 'A* + FSM', en: 'A* + FSM' }, { fr: 'Debug visuel', en: 'Visual debug' }],
  },
];

const I18N = {
  fr: {
    nav: { home: 'ACCUEIL', projects: 'PROJETS', about: 'À PROPOS', contact: 'CONTACT' },
    hero: {
      role: 'GAME DEVELOPER',
      tag: "Je conçois des expériences interactives où la mécanique raconte l'histoire.",
      cta: 'VOIR LES PROJETS',
      ctaContact: 'ME CONTACTER',
      featured: 'PROJET MIS EN AVANT',
      scroll: 'DÉFILER',
    },
    sections: {
      games: 'JEUX', engine: 'MOTEUR', tools: 'OUTILS',
      projects: 'PROJETS', selected: 'PROJETS SÉLECTIONNÉS',
      about: 'À PROPOS', contact: 'CONTACT',
      role: 'RÔLE', team: 'ÉQUIPE', duration: 'DURÉE', tech: 'TECHNO', year: 'ANNÉE',
      challenges: 'DÉFIS', pillars: 'PILIERS DESIGN',
      close: 'FERMER', viewProject: 'VOIR LE PROJET',
      viewAll: 'TOUS LES PROJETS',
    },
    about: {
      title: 'À PROPOS',
      bio: "Passionné de jeux vidéo, je combine créativité et compétences techniques pour créer des expériences interactives. Mon objectif : repousser mes limites pour concevoir des jeux qui marquent.",
      stack: 'STACK PRINCIPALE',
      interests: 'CENTRES D\'INTÉRÊT',
    },
    contact: {
      title: 'TRAVAILLONS ENSEMBLE',
      sub: 'Disponible pour collaborations, stages et opportunités junior.',
      email: 'Email',
      copy: 'COPIER',
      copied: 'COPIÉ !',
    },
  },
  en: {
    nav: { home: 'HOME', projects: 'PROJECTS', about: 'ABOUT', contact: 'CONTACT' },
    hero: {
      role: 'GAME DEVELOPER',
      tag: 'I design interactive experiences where mechanics tell the story.',
      cta: 'SEE PROJECTS',
      ctaContact: 'GET IN TOUCH',
      featured: 'FEATURED PROJECT',
      scroll: 'SCROLL',
    },
    sections: {
      games: 'GAMES', engine: 'ENGINE', tools: 'TOOLS',
      projects: 'PROJECTS', selected: 'SELECTED WORK',
      about: 'ABOUT', contact: 'CONTACT',
      role: 'ROLE', team: 'TEAM', duration: 'DURATION', tech: 'TECH', year: 'YEAR',
      challenges: 'CHALLENGES', pillars: 'DESIGN PILLARS',
      close: 'CLOSE', viewProject: 'VIEW PROJECT',
      viewAll: 'ALL PROJECTS',
    },
    about: {
      title: 'ABOUT',
      bio: "Video-game enthusiast, combining creativity and technical skills to craft interactive experiences. My goal: push my limits to design games that resonate.",
      stack: 'MAIN STACK',
      interests: 'INTERESTS',
    },
    contact: {
      title: "LET'S WORK TOGETHER",
      sub: 'Available for collaborations, internships and junior opportunities.',
      email: 'Email',
      copy: 'COPY',
      copied: 'COPIED!',
    },
  },
};

const STACK = ['Unreal Engine 5', 'Unity', 'C++', 'C#', 'Blueprints', 'OpenGL', 'PhysX', 'Lua', 'Git'];
const INTERESTS_FR = ['Gameplay design', 'Architecture moteur', 'Outils pour designers', 'Game feel', 'IA de jeu'];
const INTERESTS_EN = ['Gameplay design', 'Engine architecture', 'Tools for designers', 'Game feel', 'Game AI'];

window.PORTFOLIO_DATA = { PROJECTS, I18N, STACK, INTERESTS_FR, INTERESTS_EN };
